name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  convex_bottom_bar: ^3.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  carousel_slider: 4.0.0



  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LaQily.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/     # تحميل كل الصور داخل هذا المجلد تلقائيًا
    - assets/videos/